rgname = "RG1"
loc = "East US"
vnet = "Vnet1"
subnet_address = ["11.0.0.0/24"]
subnet_name = "subnet1"
vnet_address = ["11.0.0.0/16"]
nic = "NIC"
pip = "pip1"
NSG = "NSG1"
vmname = "VM1"
organization = "TS"
environment = "Dev"
app = "ADO"
tier = "Web"
tagging = {
    CreatedBy = "Trustedsavvy Team"
    CostCenter = 123
    Org = "TS"
  }